[plugins]

binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka"}
hildan-github-changelog = { id = "org.hildan.github.changelog", version.ref = "hildan-github-changelog-plugin"}
hildan-kotlin-publish = { id = "org.hildan.kotlin-publish", version.ref = "hildan-kotlin-publish-plugin"}
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin"}
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish-plugin" }
vyarus-github-info = { id = "ru.vyarus.github-info", version.ref = "vyarus-github-info-plugin" }

[versions]

binary-compatibility-validator = "0.18.0"
dokka = "2.0.0"
hildan-kotlin-publish-plugin = "1.7.0"
hildan-github-changelog-plugin = "2.2.0"
kotlin = "2.1.21"
kotlinpoet = "2.2.0"
kotlinx-atomicfu = "0.27.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.1"
ktor = "3.1.3"
nexus-publish-plugin = "2.0.0"
slf4j = "2.0.17"
testcontainers = "1.21.1"
vyarus-github-info-plugin = "2.0.0"

[libraries]

kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet"}
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j"}
testcontainers-base = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
